# Repository settings for SecureByDefault
# Managed via GitHub Settings Action

repository:
  # Repository metadata
  name: securebydefault
  description: A curated collection of secure-by-default PowerShell scripts and tools
  homepage: https://github.com/aarlotta/securebydefault
  topics: powershell,security,automation,devops,infrastructure
  has_wiki: false
  has_issues: true
  has_projects: false
  default_branch: main

  # Merge settings
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: false
  delete_branch_on_merge: true

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Pester Tests"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      restrictions:
        users: []
        teams: []
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: security
    color: ff0000
    description: Security-related issue or enhancement
  - name: documentation
    color: 0075ca
    description: Documentation improvements
  - name: good first issue
    color: 7057ff
    description: Good for newcomers 