name: Apply Repository Settings

on:
  push:
    branches:
      - main
    paths:
      - '.github/settings.yml'

jobs:
  apply-settings:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Apply repository settings
        uses: reitermarkus/repo-settings@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/settings.yml 