name: Apply Repository Settings

on:
  push:
    branches:
      - main
    paths:
      - '.github/settings.yml'

permissions:
  contents: read
  actions: read
  administration: write

jobs:
  apply-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Debug - Print Event Payload
        run: |
          echo "Event payload:"
          cat $GITHUB_EVENT_PATH
          echo "---"

      - name: Debug - Check Current Protection
        run: |
          gh api repos/${{ github.repository }}/branches/main/protection

      - name: Apply repository settings
        uses: reitermarkus/repo-settings@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          settings_file: .github/settings.yml 