name: Lint GitHub Settings File

on:
  push:
    paths:
      - '.github/settings.yml'
  pull_request:
    paths:
      - '.github/settings.yml'

jobs:
  lint-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run yamllint on settings.yml
        run: |
          mkdir -p .github/lint-logs
          yamllint .github/settings.yml > .github/lint-logs/settings-lint.log || true

      - name: Upload lint results
        uses: actions/upload-artifact@v4
        with:
          name: settings-lint-log
          path: .github/lint-logs/settings-lint.log 